### PR TITLE
Thai food

### PR DESCRIPTION
**Pull request by TAGCH**
Please review my pull request before merging the 'thai-food' branch to the 'main' branch.

### CODE REVIEW

**Comment by oaoak** [comment]
No conflict. Approve merging.

**Review by ChamarakGajaseni — APPROVED** [review]
no conflict, checked

**Comment by caneledip** [comment]
Approve merging.

**Review by oaoak — APPROVED** [review]
Approve.

**Review by caneledip — APPROVED** [review]
Approve merging. Nice picture

**Pull request merged**
